-- MySQL Script generated by MySQL Workbench
-- Thu Apr 30 17:53:24 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quant_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quant_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quant_db` DEFAULT CHARACTER SET utf8 ;
USE `quant_db` ;

-- -----------------------------------------------------
-- Table `quant_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quant_db`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quant_db`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quant_db`.`stocks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ticker` VARCHAR(50) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `market` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ticker_UNIQUE` (`ticker` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quant_db`.`watch_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quant_db`.`watch_lists` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `stock_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_watch_list_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_watch_list_stocks1_idx` (`stock_id` ASC) VISIBLE,
  CONSTRAINT `fk_watch_list_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `quant_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_watch_list_stocks1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `quant_db`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quant_db`.`portfolios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quant_db`.`portfolios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_portfolios_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_portfolios_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quant_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quant_db`.`portfolio_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quant_db`.`portfolio_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `portfolio_id` BIGINT NOT NULL,
  `stock_id` BIGINT NOT NULL,
  `avg_price` DECIMAL(15,2) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_portfolio_items_portfolios1_idx` (`portfolio_id` ASC) VISIBLE,
  INDEX `fk_portfolio_items_stocks1_idx` (`stock_id` ASC) VISIBLE,
  CONSTRAINT `fk_portfolio_items_portfolios1`
    FOREIGN KEY (`portfolio_id`)
    REFERENCES `quant_db`.`portfolios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portfolio_items_stocks1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `quant_db`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quant_db`.`price_histories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quant_db`.`price_histories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `stock_id` BIGINT NOT NULL,
  `date` DATE NOT NULL,
  `open_price` DECIMAL(15,2) NOT NULL,
  `close_price` DECIMAL(15,2) NOT NULL,
  `high_price` DECIMAL(15,2) NOT NULL,
  `low_price` DECIMAL(15,2) NOT NULL,
  `volume` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_price_histories_stocks1_idx` (`stock_id` ASC) VISIBLE,
  UNIQUE INDEX `idx_stock_data` (`stock_id` ASC, `date` ASC) VISIBLE,
  CONSTRAINT `fk_price_histories_stocks1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `quant_db`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quant_db`.`trades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quant_db`.`trades` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `portfolio_id` BIGINT NOT NULL,
  `stock_id` BIGINT NOT NULL,
  `trade_type` VARCHAR(20) NOT NULL DEFAULT '매수 or 매도',
  `price` DECIMAL(15,2) NOT NULL,
  `quantity` INT NOT NULL,
  `trade_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trades_portfolios1_idx` (`portfolio_id` ASC) VISIBLE,
  INDEX `fk_trades_stocks1_idx` (`stock_id` ASC) VISIBLE,
  CONSTRAINT `fk_trades_portfolios1`
    FOREIGN KEY (`portfolio_id`)
    REFERENCES `quant_db`.`portfolios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trades_stocks1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `quant_db`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `quant_db`.`stock_classification`
-- DB-06 분류 결과 저장 / DB-09에서 전략 매핑에 사용됨
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quant_db`.`stock_classification` (
  `id`            BIGINT       NOT NULL AUTO_INCREMENT,
  `stock_id`      BIGINT       NOT NULL,
  `ticker`        VARCHAR(50)  NOT NULL,
  `strategy_type` VARCHAR(50)  NOT NULL,  -- TREND_FOLLOWING / MEAN_REVERSION / MOMENTUM / VOLATILITY_BREAKOUT
  `score`         DECIMAL(5,2) NOT NULL,
  `classified_at` DATETIME     NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_stock_classification` (`stock_id` ASC),
  CONSTRAINT `fk_classification_stocks`
    FOREIGN KEY (`stock_id`)
    REFERENCES `quant_db`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE stock_metrics 
ADD UNIQUE INDEX idx_stock_metrics (stock_id, date);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


